export const json = {
  width: 1080,
  height: 1080,
  fonts: [],
  pages: [
    {
      id: "w76qNOu-sr",
      children: [
        {
          id: "voQ9zYqhvt",
          type: "image",
          x: 0,
          y: 0,
          rotation: 0,
          opacity: 1,
          visible: true,
          locked: false,
          blurEnabled: false,
          blurRadius: 10,
          brightnessEnabled: false,
          brightness: 0,
          sepiaEnabled: false,
          grayscaleEnabled: false,
          shadowEnabled: false,
          shadowBlur: 5,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          shadowColor: "black",
          selectable: true,
          alwaysOnTop: false,
          showInExport: true,
          width: 1080,
          height: 1080,
          src:
            "https://images.unsplash.com/photo-1604147706283-d7119b5b822c?auto=format&fit=crop&q=80&w=1974&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
          cropX: 0,
          cropY: 0,
          cropWidth: 1,
          cropHeight: 1,
          cornerRadius: 0,
          flipX: false,
          flipY: false,
          clipSrc: "",
          borderColor: "black",
          borderSize: 0
        },
        {
          id: "_UpqKWLYBM",
          type: "text",
          x: 189.1818723754583,
          y: 600,
          rotation: 0,
          opacity: 1,
          visible: true,
          locked: false,
          blurEnabled: false,
          blurRadius: 10,
          brightnessEnabled: false,
          brightness: 0,
          sepiaEnabled: false,
          grayscaleEnabled: false,
          shadowEnabled: false,
          shadowBlur: 5,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          shadowColor: "black",
          selectable: true,
          alwaysOnTop: false,
          showInExport: true,
          text: "For Completing",
          placeholder: "",
          fontSize: 100,
          fontFamily: "Roboto",
          fontStyle: "normal",
          fontWeight: "normal",
          textDecoration: "",
          fill: "black",
          align: "center",
          width: 736.0987892604895,
          height: 300,
          strokeWidth: 0,
          stroke: "black",
          lineHeight: 1.2,
          letterSpacing: 0
        },
        {
          id: "nAzzW9iZFy",
          type: "text",
          x: 150.99999999999994,
          y: 46.899390591100996,
          rotation: 0,
          opacity: 1,
          visible: true,
          locked: false,
          blurEnabled: false,
          blurRadius: 10,
          brightnessEnabled: false,
          brightness: 0,
          sepiaEnabled: false,
          grayscaleEnabled: false,
          shadowEnabled: false,
          shadowBlur: 5,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          shadowColor: "black",
          selectable: true,
          alwaysOnTop: false,
          showInExport: true,
          text: "Congratulations",
          placeholder: "",
          fontSize: 100,
          fontFamily: "Roboto",
          fontStyle: "normal",
          fontWeight: "normal",
          textDecoration: "",
          fill: "black",
          align: "center",
          width: 760,
          height: 96,
          strokeWidth: 0,
          stroke: "black",
          lineHeight: 1.2,
          letterSpacing: 0
        },
        {
          id: "v-QGa2tA1V",
          type: "text",
          x: 269.9999999899999,
          y: 179.75903614457823,
          rotation: 0,
          opacity: 1,
          visible: true,
          locked: false,
          blurEnabled: false,
          blurRadius: 10,
          brightnessEnabled: false,
          brightness: 0,
          sepiaEnabled: false,
          grayscaleEnabled: false,
          shadowEnabled: false,
          shadowBlur: 5,
          shadowOffsetX: 0,
          shadowOffsetY: 0,
          shadowColor: "black",
          selectable: true,
          alwaysOnTop: false,
          showInExport: true,
          text: "to",
          placeholder: "",
          fontSize: 80,
          fontFamily: "Roboto",
          fontStyle: "normal",
          fontWeight: "normal",
          textDecoration: "",
          fill: "black",
          align: "center",
          width: 600,
          height: 96,
          strokeWidth: 0,
          stroke: "black",
          lineHeight: 1.2,
          letterSpacing: 0
        }
        // ,
        // {
        //   id: "Z40u2lixXW",
        //   type: "text",
        //   x: 125.99999999999994,
        //   y: 300.3979211431999,
        //   rotation: 0,
        //   opacity: 1,
        //   visible: true,
        //   locked: false,
        //   blurEnabled: false,
        //   blurRadius: 10,
        //   brightnessEnabled: false,
        //   brightness: 0,
        //   sepiaEnabled: false,
        //   grayscaleEnabled: false,
        //   shadowEnabled: false,
        //   shadowBlur: 5,
        //   shadowOffsetX: 0,
        //   shadowOffsetY: 0,
        //   shadowColor: "black",
        //   selectable: true,
        //   alwaysOnTop: false,
        //   showInExport: true,
        //   text: "{name}",
        //   placeholder: "",
        //   fontSize: 184,
        //   fontFamily: "Alata",
        //   fontStyle: "normal",
        //   fontWeight: "normal",
        //   textDecoration: "",
        //   fill: "black",
        //   align: "center",
        //   width: 828,
        //   height: 220.79999999999998,
        //   strokeWidth: 0,
        //   stroke: "black",
        //   lineHeight: 1.2,
        //   letterSpacing: 0
        // }
      ]
      // background: "lightblue"
    }
  ]
};
